spring:
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    testWhileIdle: true
    test-on-borrow: true
    validationQuery: SELECT 1
#    this should be passed as ENV variable
    url: jdbc:mysql://sql240.main-hosting.eu:3306/u994816388_homework?useSSL=false
    username: u994816388_homework
    password: DatabasePassword1234
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          order_updates: true
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    web: DEBUG
